### ISSUE TITLE
ReflectorMap fails for Objects with Classes loaded by custom ClassLoader

### ISSUE THREAD

**Issue by Clashsoft** [fujaba/fulibYaml#7]
First occurred in FulibScenarios, when attempting to generate object diagrams in the Webservice. Because generated classes are compiled to a random directory, a custom ClassLoader is required to load them.

# Reproduce

1. check out fujaba/fulibScenarios@2536e6730453c708ffdfbbf8fad74e8bb3dba1f2.
2. open and run the `WebService` class.
3. open the web app.
4. open the browser developer console.
5. add a diagram sentence to the scenario editor, like `![alice](alice.png)`.
6. trigger compile and run.
7. check the developer console. It will contain this stack trace:

```
test(webapp.StartUp)failed:
java.lang.RuntimeException: ReflectorMap could not find class description for Player
searching in 
   webapp
You might add more packages to the construction of the ReflectorMap / YamlIdMap 
or you might move the missing class into the common model package.
	at org.fulib.yaml.ReflectorMap.getReflector(ReflectorMap.java:120)
	at org.fulib.yaml.ReflectorMap.getReflector(ReflectorMap.java:59)
	at org.fulib.yaml.YamlIdMap.getReflector(YamlIdMap.java:1033)
	at org.fulib.yaml.YamlIdMap.collectObjects(YamlIdMap.java:1163)
	at org.fulib.tools.ObjectDiagrams.dump(ObjectDiagrams.java:116)
	at org.fulib.tools.ObjectDiagrams.dumpSVG(ObjectDiagrams.java:100)
	at webapp.StartUp.test(StartUp.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at org.fulib.scenarios.tool.JavaCompiler.runTests(JavaCompiler.java:110)
	at org.fulib.scenarios.tool.JavaCompiler.genCompileRun(JavaCompiler.java:163)
	at org.fulib.scenarios.WebService.runCodeGen(WebService.java:62)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

# Potential Fix

The relevant line is here:

https://github.com/fujaba/fulibYaml/blob/4ef4bb04f475b91e18cd15c018d8d7c54b88a33f/src/main/java/org/fulib/yaml/ReflectorMap.java#L76

A fix could utilise the class object which is already available here, but discarded subsequently:

https://github.com/fujaba/fulibYaml/blob/4ef4bb04f475b91e18cd15c018d8d7c54b88a33f/src/main/java/org/fulib/yaml/ReflectorMap.java#L57

However, the [`Reflector`](https://github.com/fujaba/fulibYaml/blob/4ef4bb04f475b91e18cd15c018d8d7c54b88a33f/src/main/java/org/fulib/yaml/Reflector.java) class also uses `Class.forName`, so it needs to be changed too.

**Comment by azuendorf** [comment]
Is this still open?

**Comment by Clashsoft** [comment]
If df99a807f0cb74dbb6bf4e7c9b3b7de24a96458a fixes it, then probably not.
